/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface GraphNodeDto {
  id: number
  label: string
  category: string
  createdAt: string
  decayScore: number
  metadata?: string
}
export interface RetrievalWeightsDto {
  temporalWeight: number
  personalWeight: number
  technicalWeight: number
  emotionalWeight: number
}
export interface RetrievalResultDto {
  source: string
  text: string
  score: number
  tokens: number
  createdAt: string
  category?: string
  tier?: string
}
export interface RetrievalCandidateDto {
  text: string
  createdAt?: string
  category?: string
  nodeId?: number
  tier?: string
}
export interface PipelineLayersDto {
  episodes: number
  graphNodes: number
  fingerprintEntries: number
  fingerprintMode: string
  includedLayers: Array<string>
}
export interface PipelineResultDto {
  systemPrompt: string
  tokenCount: number
  layers: PipelineLayersDto
}
export interface ClassifierResultDto {
  temporalWeight: number
  personalWeight: number
  technicalWeight: number
  emotionalWeight: number
  messageType: string
  sessionState: string
}
export interface FingerprintEntryDto {
  key: string
  value: string
}
export interface FingerprintResultDto {
  entries: Array<FingerprintEntryDto>
  deltaOnly: boolean
  compiledAt: string
}
export interface MemoryRecordDto {
  id: number
  tier: string
  createdAt: string
  expiresAt?: string
  text: string
}
export interface MemorySnapshotDto {
  tier1: Array<MemoryRecordDto>
  tier2: Array<MemoryRecordDto>
  tier3: Array<MemoryRecordDto>
}
export interface MemoryCompressionDto {
  compressed: number
  skipped: number
}
export interface MemoryCrystallizationDto {
  processedSummaries: number
  factsCreated: number
}
export interface MemoryStatsDto {
  tier1Count: number
  tier2Count: number
  tier3Count: number
  lastCompress?: string
  lastCrystallize?: string
}
export declare class HiveCtxEngine {
  constructor(storagePath: string, budgetTokens?: number | undefined | null)
  get storagePath(): string
  get budgetTokens(): number | null
  graphAddNode(text: string, category?: string | undefined | null): NapiResult
  graphAddEdge(sourceNodeId: number, targetNodeId: number, relationshipType: string): NapiResult
  graphQuery(pattern?: string | undefined | null, category?: string | undefined | null, limit?: number | undefined | null): NapiResult
  graphTraverse(startNodeId: number, maxHops: number): NapiResult
  graphDecayUpdate(): NapiResult
  memoryStore(text: string): NapiResult
  memoryRetrieve(limit?: number | undefined | null): NapiResult
  memoryCompress(): NapiResult
  memoryCrystallize(): NapiResult
  memoryStats(): NapiResult
  pipelineBuild(message: string, userProfile: Record<string, string>, tokenBudget?: number | undefined | null): NapiResult
  retrievalSearch(text: string, weights: RetrievalWeightsDto, limit?: number | undefined | null): NapiResult
  retrievalRank(text: string, weights: RetrievalWeightsDto, candidates: Array<RetrievalCandidateDto>, limit?: number | undefined | null): NapiResult
  classifyMessage(text: string): NapiResult
  fingerprintCompile(profile: Record<string, string>): NapiResult
}
